name: Elements Workflow

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the code
        uses: actions/checkout@v2

      - name: Setup the flutter environment.
        uses: subosito/flutter-action@v1

      - name: Analyze Code
        run: flutter analyze

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the code
        uses: actions/checkout@v2

      - name: Setup the flutter environment.
        uses: subosito/flutter-action@v1
      
      - name: Test Modules
        run: flutter test